[package]
name = "deployment"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
serde = { version = "1.0.197", features = ["derive"] }
tide = "0.16.0"
zip = "0.6.6"
