name: Deploy website
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened]
    
jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache packages in node_modules
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
            ./.next/cache
            ~/.cache/yarn
          key: ${{ runner.OS }}-node-${{ github.sha }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: install
        run: yarn install

      - name: build
        run: yarn build

      - name: Tattoo, package and deploy to test server
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "Commit SHA: ${GITHUB_SHA}" > ./out/info.txt
          echo "Ref: ${GITHUB_REF}" >> ./out/info.txt
          cd out
          zip ../out.zip *
          cd ..
          curl -u ${{ secrets.TEST_SERVER_CRED }} -X POST -H "Content-Type: application/zip" --data-binary @out.zip ${{ secrets.TEST_SERVER_URL }}

      - name: Deploy files via FTP
        uses: xarses/lftp-upload-action@v0.2.0
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          mirror_args: --no-perms --overwrite
          local_path: out
          remote_path: public_html
